package student_management_system;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Manages all persistent data operations for students using JDBC and MySQL.
 * This class acts as the Data Access Object (DAO) for the application.
 */
public class StudentManager 
{
	// =================================================================
    // 				        I. CONFIGURATION & CONNECTION
    // =================================================================

	// --- Database Credentials ---
	private static final String JDBC_URL = "jdbc:mysql://localhost:3306/student_db";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "root1234";
	
	/**
	 * Constructor: Attempts to establish a connection to the database.
	 */
	public StudentManager() 
	{
		try (Connection conn = this.getConnection()) 
		{
            if (conn != null) 
            {
                System.out.println("✅ Database connection established successfully.");
            }
        } 
		catch (SQLException e) 
		{
            System.out.println("❌ Error connecting to the database. Check credentials and server status: " + e.getMessage());
        }
    }
	
	/**
	 * Helper method to establish a new database connection.
	 * @return A valid Connection object.
	 * @throws SQLException if a database access error occurs.
	 */
	private Connection getConnection() throws SQLException 
	{
        return DriverManager.getConnection(JDBC_URL, DB_USER, DB_PASSWORD);
    }
	
	
	// =================================================================
    // 				        II. CRUD OPERATIONS (Public API)
    // =================================================================

	/**
	 * Adds a new student record to the MySQL database.
	 * @param name The student's name.
	 * @param grade The student's grade (1-4).
	 */
	public void addStudent(String name, int grade) 
	{
		// Note: The ID is automatically generated by MySQL AUTO_INCREMENT.
		String sql = "INSERT INTO students (name, grade) VALUES (?, ?)";
		
		try (Connection conn = getConnection();
		     PreparedStatement pstmt = conn.prepareStatement(sql)) 
		{
		    // Set parameters using PreparedStatement to prevent SQL injection
		    pstmt.setString(1, name);
		    pstmt.setInt(2, grade);

		    int rowsAffected = pstmt.executeUpdate();

		    if (rowsAffected > 0) 
		    {
		        System.out.println("✅ Student added successfully!");
		    } 
		    else 
		    {
		        System.out.println("❌ Failed to add student.");
		    }
		} 
		catch (SQLException e) 
		{
		    System.out.println("❌ Database Error while adding student: " + e.getMessage());
		}
    }
	
	/**
	 * Retrieves all student records from the database.
	 * @return A List of all Student objects.
	 */
	public List<Student> viewAllStudents() 
	{
		List<Student> studentList = new ArrayList<>();
	    String sql = "SELECT id, name, grade FROM students ORDER BY id ASC";

	    // Try-With-Resources automatically closes Connection, Statement, and ResultSet
	    try (Connection conn = getConnection();
	         Statement stmt = conn.createStatement();
	         ResultSet rs = stmt.executeQuery(sql)) 
	    { 
	        while (rs.next()) 
	        {
	            // Map ResultSet columns back to a Student object
	            int id = rs.getInt("id");
	            String name = rs.getString("name");
	            int grade = rs.getInt("grade");

	            studentList.add(new Student(id, name, grade));
	        }
	    } 
	    catch (SQLException e) 
	    {
	        System.out.println("❌ Database Error while viewing students: " + e.getMessage());
	    }
	    
	    return studentList;
    }
	
	/**
	 * Searches the database for a student by ID.
	 * @param id The ID of the student to search for.
	 * @return The found Student object, or null if not found.
	 */
	public Student findStudent(int id) 
	{
		String sql = "SELECT id, name, grade FROM students WHERE id = ?";

	    try (Connection conn = getConnection();
	         PreparedStatement pstmt = conn.prepareStatement(sql)) 
	    {
	        pstmt.setInt(1, id); 

	        try (ResultSet rs = pstmt.executeQuery()) 
	        {
	            if (rs.next()) 
	            {
	                String name = rs.getString("name");
	                int grade = rs.getInt("grade");
	                
	                return new Student(id, name, grade);
	            }
	        }
	    } 
	    catch (SQLException e) 
	    {
	        System.out.println("❌ Database Error while searching for student: " + e.getMessage());
	    }
	    
	    return null;
    }
	
	
	// =================================================================
    // 				        III. UTILITY METHODS
    // =================================================================

	/**
	 * Checks if the 'students' table is empty using SQL COUNT.
	 * @return true if the table has zero records, false otherwise.
	 */
	public boolean isEmpty() 
	{
	    String sql = "SELECT COUNT(*) FROM students";
	    
	    try (Connection conn = getConnection();
	         Statement stmt = conn.createStatement();
	         ResultSet rs = stmt.executeQuery(sql)) 
	    {
	        
	        if (rs.next()) 
	        {
	            int count = rs.getInt(1);
	            return count == 0;
	        }
	    } 
	    catch (SQLException e) 
	    {
	        // Defensive coding: If we can't connect/query, assume the list is empty
            // or unavailable to prevent cascading errors in the Main class.
	        System.out.println("❌ Database Error during isEmpty check: " + e.getMessage());
	    }
        
	    // Default to true upon error, preventing unnecessary attempts to search/view.
	    return true; 
	}
}